# Server config
server:
  port: ${PORT:8080}

# Spring config
spring:
  application:
    name: article-service
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# Ribbon config
ribbon:
  eureka:
    enabled: true

# Jaeger config  
opentracing:
  jaeger:
    http-sender:
      url: '${JAEGER_URL:http://jaeger-collector.istio-system.svc:14268}/api/traces'
    log-spans: true
